export const icons = [
  {
    id: "activity",
    name: "Activity",
    category: "General",
    importName: "Activity",
  },
  {
    id: "airplay",
    name: "Airplay",
    category: "Media",
    importName: "Airplay",
  },
  {
    id: "alert-circle",
    name: "Alert Circle",
    category: "Alert",
    importName: "AlertCircle",
  },
  {
    id: "alert-octagon",
    name: "Alert Octagon",
    category: "Alert",
    importName: "AlertOctagon",
  },
  {
    id: "alert-triangle",
    name: "Alert Triangle",
    category: "Alert",
    importName: "AlertTriangle",
  },
  {
    id: "archive",
    name: "Archive",
    category: "Files",
    importName: "Archive",
  },
  {
    id: "arrow-down",
    name: "Arrow Down",
    category: "Arrows",
    importName: "ArrowDown",
  },
  {
    id: "arrow-left",
    name: "Arrow Left",
    category: "Arrows",
    importName: "ArrowLeft",
  },
  {
    id: "arrow-right",
    name: "Arrow Right",
    category: "Arrows",
    importName: "ArrowRight",
  },
  {
    id: "arrow-up",
    name: "Arrow Up",
    category: "Arrows",
    importName: "ArrowUp",
  },
  {
    id: "at-sign",
    name: "At Sign",
    category: "Communication",
    importName: "AtSign",
  },
  {
    id: "award",
    name: "Award",
    category: "Achievements",
    importName: "Award",
  },
  {
    id: "bell",
    name: "Bell",
    category: "Notifications",
    importName: "Bell",
  },
  {
    id: "bookmark",
    name: "Bookmark",
    category: "General",
    importName: "Bookmark",
  },
  {
    id: "camera",
    name: "Camera",
    category: "Media",
    importName: "Camera",
  },
  {
    id: "check",
    name: "Check",
    category: "General",
    importName: "Check",
  },
  {
    id: "check-circle",
    name: "Check Circle",
    category: "General",
    importName: "CheckCircle",
  },
  {
    id: "chevron-down",
    name: "Chevron Down",
    category: "Arrows",
    importName: "ChevronDown",
  },
  {
    id: "chevron-left",
    name: "Chevron Left",
    category: "Arrows",
    importName: "ChevronLeft",
  },
  {
    id: "chevron-right",
    name: "Chevron Right",
    category: "Arrows",
    importName: "ChevronRight",
  },
  {
    id: "chevron-up",
    name: "Chevron Up",
    category: "Arrows",
    importName: "ChevronUp",
  },
  {
    id: "clock",
    name: "Clock",
    category: "Time",
    importName: "Clock",
  },
  {
    id: "cloud",
    name: "Cloud",
    category: "Weather",
    importName: "Cloud",
  },
  {
    id: "code",
    name: "Code",
    category: "Development",
    importName: "Code",
  },
  {
    id: "command",
    name: "Command",
    category: "Development",
    importName: "Command",
  },
  {
    id: "copy",
    name: "Copy",
    category: "Files",
    importName: "Copy",
  },
  {
    id: "credit-card",
    name: "Credit Card",
    category: "Payment",
    importName: "CreditCard",
  },
  {
    id: "database",
    name: "Database",
    category: "Development",
    importName: "Database",
  },
  {
    id: "delete",
    name: "Delete",
    category: "Actions",
    importName: "Delete",
  },
  {
    id: "disc",
    name: "Disc",
    category: "Media",
    importName: "Disc",
  },
  {
    id: "download",
    name: "Download",
    category: "Files",
    importName: "Download",
  },
  {
    id: "edit",
    name: "Edit",
    category: "Actions",
    importName: "Edit",
  },
  {
    id: "external-link",
    name: "External Link",
    category: "Links",
    importName: "ExternalLink",
  },
  {
    id: "eye",
    name: "Eye",
    category: "Visibility",
    importName: "Eye",
  },
  {
    id: "file",
    name: "File",
    category: "Files",
    importName: "File",
  },
  {
    id: "filter",
    name: "Filter",
    category: "Actions",
    importName: "Filter",
  },
  {
    id: "flag",
    name: "Flag",
    category: "General",
    importName: "Flag",
  },
  {
    id: "folder",
    name: "Folder",
    category: "Files",
    importName: "Folder",
  },
  {
    id: "globe",
    name: "Globe",
    category: "General",
    importName: "Globe",
  },
  {
    id: "heart",
    name: "Heart",
    category: "General",
    importName: "Heart",
  },
  {
    id: "help-circle",
    name: "Help Circle",
    category: "Help",
    importName: "HelpCircle",
  },
  {
    id: "home",
    name: "Home",
    category: "General",
    importName: "Home",
  },
  {
    id: "image",
    name: "Image",
    category: "Media",
    importName: "Image",
  },
  {
    id: "info",
    name: "Info",
    category: "General",
    importName: "Info",
  },
  {
    id: "key",
    name: "Key",
    category: "Security",
    importName: "Key",
  },
  {
    id: "layers",
    name: "Layers",
    category: "General",
    importName: "Layers",
  },
  {
    id: "life-buoy",
    name: "Life Buoy",
    category: "Help",
    importName: "LifeBuoy",
  },
  {
    id: "link",
    name: "Link",
    category: "Links",
    importName: "Link",
  },
  {
    id: "list",
    name: "List",
    category: "General",
    importName: "List",
  },
  {
    id: "loader",
    name: "Loader",
    category: "General",
    importName: "Loader",
  },
  {
    id: "lock",
    name: "Lock",
    category: "Security",
    importName: "Lock",
  },
  {
    id: "log-in",
    name: "Log In",
    category: "Authentication",
    importName: "LogIn",
  },
  {
    id: "log-out",
    name: "Log Out",
    category: "Authentication",
    importName: "LogOut",
  },
  {
    id: "mail",
    name: "Mail",
    category: "Communication",
    importName: "Mail",
  },
  {
    id: "map",
    name: "Map",
    category: "Location",
    importName: "Map",
  },
  {
    id: "menu",
    name: "Menu",
    category: "Navigation",
    importName: "Menu",
  },
  {
    id: "message-circle",
    name: "Message Circle",
    category: "Communication",
    importName: "MessageCircle",
  },
  {
    id: "message-square",
    name: "Message Square",
    category: "Communication",
    importName: "MessageSquare",
  },
  {
    id: "mic",
    name: "Mic",
    category: "Media",
    importName: "Mic",
  },
  {
    id: "minus",
    name: "Minus",
    category: "Actions",
    importName: "Minus",
  },
  {
    id: "monitor",
    name: "Monitor",
    category: "Devices",
    importName: "Monitor",
  },
  {
    id: "moon",
    name: "Moon",
    category: "Theme",
    importName: "Moon",
  },
  {
    id: "more-horizontal",
    name: "More Horizontal",
    category: "Actions",
    importName: "MoreHorizontal",
  },
  {
    id: "more-vertical",
    name: "More Vertical",
    category: "Actions",
    importName: "MoreVertical",
  },
  {
    id: "music",
    name: "Music",
    category: "Media",
    importName: "Music",
  },
  {
    id: "navigation",
    name: "Navigation",
    category: "Location",
    importName: "Navigation",
  },
  {
    id: "paperclip",
    name: "Paperclip",
    category: "Files",
    importName: "Paperclip",
  },
  {
    id: "pause",
    name: "Pause",
    category: "Media",
    importName: "Pause",
  },
  {
    id: "phone",
    name: "Phone",
    category: "Communication",
    importName: "Phone",
  },
  {
    id: "play",
    name: "Play",
    category: "Media",
    importName: "Play",
  },
  {
    id: "plus",
    name: "Plus",
    category: "Actions",
    importName: "Plus",
  },
  {
    id: "power",
    name: "Power",
    category: "Actions",
    importName: "Power",
  },
  {
    id: "refresh-ccw",
    name: "Refresh Ccw",
    category: "Actions",
    importName: "RefreshCcw",
  },
  {
    id: "repeat",
    name: "Repeat",
    category: "Media",
    importName: "Repeat",
  },
  {
    id: "save",
    name: "Save",
    category: "Files",
    importName: "Save",
  },
  {
    id: "search",
    name: "Search",
    category: "Actions",
    importName: "Search",
  },
  {
    id: "send",
    name: "Send",
    category: "Communication",
    importName: "Send",
  },
  {
    id: "settings",
    name: "Settings",
    category: "General",
    importName: "Settings",
  },
  {
    id: "share",
    name: "Share",
    category: "Actions",
    importName: "Share",
  },
  {
    id: "shield",
    name: "Shield",
    category: "Security",
    importName: "Shield",
  },
  {
    id: "shopping-cart",
    name: "Shopping Cart",
    category: "E-commerce",
    importName: "ShoppingCart",
  },
  {
    id: "star",
    name: "Star",
    category: "General",
    importName: "Star",
  },
  {
    id: "sun",
    name: "Sun",
    category: "Theme",
    importName: "Sun",
  },
  {
    id: "tag",
    name: "Tag",
    category: "E-commerce",
    importName: "Tag",
  },
  {
    id: "target",
    name: "Target",
    category: "General",
    importName: "Target",
  },
  {
    id: "terminal",
    name: "Terminal",
    category: "Development",
    importName: "Terminal",
  },
  {
    id: "thumbs-down",
    name: "Thumbs Down",
    category: "Reactions",
    importName: "ThumbsDown",
  },
  {
    id: "thumbs-up",
    name: "Thumbs Up",
    category: "Reactions",
    importName: "ThumbsUp",
  },
  {
    id: "toggle-left",
    name: "Toggle Left",
    category: "UI",
    importName: "ToggleLeft",
  },
  {
    id: "toggle-right",
    name: "Toggle Right",
    category: "UI",
    importName: "ToggleRight",
  },
  {
    id: "trash",
    name: "Trash",
    category: "Actions",
    importName: "Trash",
  },
  {
    id: "trending-down",
    name: "Trending Down",
    category: "Charts",
    importName: "TrendingDown",
  },
  {
    id: "trending-up",
    name: "Trending Up",
    category: "Charts",
    importName: "TrendingUp",
  },
  {
    id: "upload",
    name: "Upload",
    category: "Files",
    importName: "Upload",
  },
  {
    id: "user",
    name: "User",
    category: "Users",
    importName: "User",
  },
  {
    id: "user-plus",
    name: "User Plus",
    category: "Users",
    importName: "UserPlus",
  },
  {
    id: "user-x",
    name: "User X",
    category: "Users",
    importName: "UserX",
  },
  {
    id: "users",
    name: "Users",
    category: "Users",
    importName: "Users",
  },
  {
    id: "video",
    name: "Video",
    category: "Media",
    importName: "Video",
  },
  {
    id: "voicemail",
    name: "Voicemail",
    category: "Communication",
    importName: "Voicemail",
  },
  {
    id: "volume",
    name: "Volume",
    category: "Media",
    importName: "Volume",
  },
  {
    id: "volume-1",
    name: "Volume 1",
    category: "Media",
    importName: "Volume1",
  },
  {
    id: "volume-2",
    name: "Volume 2",
    category: "Media",
    importName: "Volume2",
  },
  {
    id: "volume-x",
    name: "Volume X",
    category: "Media",
    importName: "VolumeX",
  },
  {
    id: "watch",
    name: "Watch",
    category: "Devices",
    importName: "Watch",
  },
  {
    id: "wifi",
    name: "Wifi",
    category: "Connectivity",
    importName: "Wifi",
  },
  {
    id: "wifi-off",
    name: "Wifi Off",
    category: "Connectivity",
    importName: "WifiOff",
  },
  {
    id: "x",
    name: "X",
    category: "Actions",
    importName: "X",
  },
  {
    id: "x-circle",
    name: "X Circle",
    category: "Actions",
    importName: "XCircle",
  },
  {
    id: "zap",
    name: "Zap",
    category: "General",
    importName: "Zap",
  },
  {
    id: "zoom-in",
    name: "Zoom In",
    category: "Actions",
    importName: "ZoomIn",
  },
  {
    id: "zoom-out",
    name: "Zoom Out",
    category: "Actions",
    importName: "ZoomOut",
  },
];
